# Docker-like setup that serves as a local drop-in for the corresponding Travis services
version: "3.7"
services:
  test:
    build: .
    user: 1000:1000
    depends_on:
      - mysql
      - postgresql
    volumes:
      - .:/app
    working_dir: /app
    environment:
      MYSQL_URL: mysql+pymysql://root@mysql/asphalttest
      POSTGRESQL_URL: postgresql+psycopg2://postgres:secret@postgresql/asphalttest
    entrypoint: dockerize -wait tcp://postgresql:5432 -wait tcp://mysql:3306 pytest

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: asphalttest
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: asphalttest
      POSTGRES_PASSWORD: secret
